version: '3.8'

services:
  anilist-data-collector:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount kaggle.json credentials file
      - ${KAGGLE_JSON_PATH:-~/.kaggle/kaggle.json}:/root/.kaggle/kaggle.json:ro
    environment:
      # Set timezone to CST (America/Chicago)
      - TZ=America/Chicago
    # Keep the container running to allow cron to execute
    tty: true
    stdin_open: true
    restart: unless-stopped
