services:
  anilist-data-collector:
    image: kdidtech/anilist-data-collector:latest
    volumes:
      # Mount kaggle.json credentials file
      - ${KAGGLE_JSON_PATH:-~/.kaggle/kaggle.json}:/root/.kaggle/kaggle.json:ro
    environment:
      # Set timezone to CST (America/Chicago)
      - TZ=America/Chicago
      # Control whether to run initially or wait for cron
      - INITIAL_RUN=true  # Set to "true" for initial run, "false" to skip
    # Keep the container running to allow cron to execute
    tty: true
    stdin_open: true
    restart: unless-stopped
